// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlGbUEoAi0xz-jkwbab1OlGhtO5efksBM',
    appId: '1:984210473869:web:a1cb31c16654b0d30cb3c4',
    messagingSenderId: '984210473869',
    projectId: 'nusantara-rasa',
    authDomain: 'nusantara-rasa.firebaseapp.com',
    storageBucket: 'nusantara-rasa.firebasestorage.app',
    measurementId: 'G-NC8HCY5NSM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQI-MJd23LNtSWys0IDA_qxlBjhk6OW14',
    appId: '1:984210473869:android:a6a2edb3acbb19c90cb3c4',
    messagingSenderId: '984210473869',
    projectId: 'nusantara-rasa',
    storageBucket: 'nusantara-rasa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-1pfqQMNUP_gazeDscwp6SdyPPKYXiiw',
    appId: '1:984210473869:ios:c793fe25195254ab0cb3c4',
    messagingSenderId: '984210473869',
    projectId: 'nusantara-rasa',
    storageBucket: 'nusantara-rasa.firebasestorage.app',
    iosClientId: '984210473869-f3c34ao1f2bvn5nrnu4a8lq99im7rhlg.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-1pfqQMNUP_gazeDscwp6SdyPPKYXiiw',
    appId: '1:984210473869:ios:c793fe25195254ab0cb3c4',
    messagingSenderId: '984210473869',
    projectId: 'nusantara-rasa',
    storageBucket: 'nusantara-rasa.firebasestorage.app',
    iosClientId: '984210473869-f3c34ao1f2bvn5nrnu4a8lq99im7rhlg.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlGbUEoAi0xz-jkwbab1OlGhtO5efksBM',
    appId: '1:984210473869:web:0bcbef960d0f2af50cb3c4',
    messagingSenderId: '984210473869',
    projectId: 'nusantara-rasa',
    authDomain: 'nusantara-rasa.firebaseapp.com',
    storageBucket: 'nusantara-rasa.firebasestorage.app',
    measurementId: 'G-0KC7LVW95S',
  );
}
